/* eslint-disable @typescript-eslint/no-explicit-any */
import { action } from "../_generated/server";
import { v } from "convex/values";
import { getBaseUrl } from "../lib/env";
import { sendViaResendOrThrow } from "../lib/resend";
import { EMAIL_TEMPLATES } from "../lib/emailTemplates";

/**
 * Email Fulfillment Actions
 *
 * Member-facing membership emails. All HTML lives in lib/emailTemplates.ts so
 * the debug tester renders exactly what members receive.
 *
 * Required env vars: RESEND_API_KEY
 */

/**
 * Send Member Fulfillment Packet Email
 *
 * Generates the fulfillment packet and membership agreement PDFs, then sends
 * them to the member with both attached.
 *
 * The PDFs are generated by the Next.js API route /api/generate-fulfillment-pdf
 * so that @react-pdf/renderer runs in the Node.js environment.
 *
 * Required env vars:
 *   RESEND_API_KEY
 *   NEXT_PUBLIC_APP_URL  (e.g. https://getidealoh.com)
 *   INTERNAL_API_SECRET  (shared secret with Next.js – omit in dev to skip auth)
 */
export const sendFulfillmentPacketEmail = action({
  args: {
    // Member data used to personalise the PDF and email body
    memberName: v.string(),
    memberFirstName: v.string(),
    memberEmail: v.string(),
    memberId: v.string(),
    planName: v.string(),
    groupCode: v.string(),
    effectiveDate: v.string(),
    // Optional fields
    subscriberId: v.optional(v.string()),
    term: v.optional(v.string()),
    memberAddress: v.optional(v.string()),
    periodicCharge: v.optional(v.string()),
    processingFee: v.optional(v.string()),
    memberServicesPhone: v.optional(v.string()),
    memberWebsite: v.optional(v.string()),
    // Per-member network URLs — forwarded to PDF so the card back matches the dashboard
    networks: v.optional(v.object({
      careington: v.object({ name: v.string(), memberUrl: v.string() }),
      dialCare:   v.object({ name: v.string(), memberUrl: v.string() }),
      toothlens:  v.object({ name: v.string(), memberUrl: v.string() }),
    })),
    // Allows callers to override the app base URL (useful in tests / staging)
    appUrl: v.optional(v.string()),
    // Which body to wrap the packet PDFs in. The attachments are identical —
    // only the message differs, e.g. the benefits-ready nudge for members who
    // enrolled but never signed in.
    templateId: v.optional(v.union(v.literal("fulfillment-packet"), v.literal("benefits-ready"))),
    // Live set-password link, for the benefits-ready body.
    activationUrl: v.optional(v.string()),
  },
  handler: async (_ctx: any, args: any) => {
    const baseUrl = args.appUrl ?? getBaseUrl();

    // ── Step 1: generate the PDFs ─────────────────────────────────────────────
    const pdfPayload = {
      memberName: args.memberName,
      memberFirstName: args.memberFirstName,
      memberEmail: args.memberEmail,
      memberId: args.memberId,
      subscriberId: args.subscriberId,
      groupCode: args.groupCode,
      planName: args.planName,
      effectiveDate: args.effectiveDate,
      term: args.term,
      memberAddress: args.memberAddress,
      periodicCharge: args.periodicCharge,
      processingFee: args.processingFee,
      memberServicesPhone: args.memberServicesPhone,
      memberWebsite: args.memberWebsite,
      networks: args.networks,
    };

    const pdfHeaders: Record<string, string> = {
      "Content-Type": "application/json",
    };
    const internalSecret = process.env.INTERNAL_API_SECRET;
    if (internalSecret) {
      pdfHeaders["Authorization"] = `Bearer ${internalSecret}`;
    }

    const pdfResponse = await fetch(
      `${baseUrl}/api/generate-fulfillment-pdf`,
      {
        method: "POST",
        headers: pdfHeaders,
        body: JSON.stringify(pdfPayload),
      }
    );

    if (!pdfResponse.ok) {
      const errText = await pdfResponse.text();
      throw new Error(
        `PDF generation failed (${pdfResponse.status}): ${errText}`
      );
    }

    const { pdf: pdfBase64, agreementPdf: agreementPdfBase64 } = await pdfResponse.json();

    // ── Step 2: send via Resend with both PDFs attached ───────────────────────
    const templateId = args.templateId ?? "fulfillment-packet";
    const body = {
      memberFirstName: args.memberFirstName,
      memberId: args.memberId,
      planName: args.planName,
      effectiveDate: args.effectiveDate,
      groupCode: args.groupCode,
      memberServicesPhone: args.memberServicesPhone ?? "(844) 679-9367",
      portalUrl: baseUrl,
    };
    const { subject, html } =
      templateId === "benefits-ready"
        ? EMAIL_TEMPLATES["benefits-ready"].render({ ...body, activationUrl: args.activationUrl })
        : EMAIL_TEMPLATES["fulfillment-packet"].render(body);

    return await sendViaResendOrThrow({
      to: args.memberEmail,
      subject,
      html,
      attachments: [
        {
          filename: "Ideal_Oral_Health_Membership_Packet.pdf",
          content: pdfBase64,
        },
        {
          filename: "Ideal_Oral_Health_Membership_Agreement.pdf",
          content: agreementPdfBase64,
        },
      ],
      tags: [{ name: "category", value: templateId }],
    });
  },
});

/**
 * Send Ideal Health Essentials Welcome Packet Email
 *
 * Generates the Essentials welcome packet (with the Balance for Life letter
 * appended) and the membership agreement, then sends both to the member.
 *
 * Mirrors sendFulfillmentPacketEmail — the PDFs are rendered by the Next.js
 * route so @react-pdf/renderer runs in Node.
 *
 * Required env vars:
 *   RESEND_API_KEY
 *   NEXT_PUBLIC_APP_URL  (e.g. https://getidealoh.com)
 *   INTERNAL_API_SECRET  (shared secret with Next.js – omit in dev to skip auth)
 */
export const sendEssentialsPacketEmail = action({
  args: {
    memberName: v.string(),
    memberFirstName: v.string(),
    memberEmail: v.string(),
    essentialsMemberNumber: v.string(),
    essentialsGroupNumber: v.string(),
    planName: v.string(),
    effectiveDate: v.string(),
    // Optional fields
    coverageType: v.optional(v.string()),
    term: v.optional(v.string()),
    memberAddress: v.optional(v.string()),
    periodicCharge: v.optional(v.string()),
    appUrl: v.optional(v.string()),
  },
  handler: async (_ctx: any, args: any) => {
    const baseUrl = args.appUrl ?? getBaseUrl();

    // ── Step 1: generate the PDFs ─────────────────────────────────────────────
    const pdfPayload = {
      memberName: args.memberName,
      memberFirstName: args.memberFirstName,
      memberEmail: args.memberEmail,
      essentialsMemberNumber: args.essentialsMemberNumber,
      essentialsGroupNumber: args.essentialsGroupNumber,
      planName: args.planName,
      coverageType: args.coverageType,
      effectiveDate: args.effectiveDate,
      term: args.term,
      memberAddress: args.memberAddress,
      periodicCharge: args.periodicCharge,
    };

    const pdfHeaders: Record<string, string> = { "Content-Type": "application/json" };
    const internalSecret = process.env.INTERNAL_API_SECRET;
    if (internalSecret) {
      pdfHeaders["Authorization"] = `Bearer ${internalSecret}`;
    }

    const pdfResponse = await fetch(`${baseUrl}/api/generate-essentials-pdf`, {
      method: "POST",
      headers: pdfHeaders,
      body: JSON.stringify(pdfPayload),
    });

    if (!pdfResponse.ok) {
      const errText = await pdfResponse.text();
      throw new Error(`Essentials PDF generation failed (${pdfResponse.status}): ${errText}`);
    }

    const { pdf: pdfBase64, agreementPdf: agreementPdfBase64 } = await pdfResponse.json();

    // ── Step 2: send via Resend with both PDFs attached ───────────────────────
    const { subject, html } = EMAIL_TEMPLATES["essentials-fulfillment-packet"].render({
      memberFirstName: args.memberFirstName,
      essentialsMemberNumber: args.essentialsMemberNumber,
      essentialsGroupNumber: args.essentialsGroupNumber,
      planName: args.planName,
      coverageType: args.coverageType ?? "Employee",
      effectiveDate: args.effectiveDate,
      memberServicesPhone: "844-433-2502",
      portalUrl: baseUrl,
    });

    return await sendViaResendOrThrow({
      to: args.memberEmail,
      subject,
      html,
      attachments: [
        {
          filename: "Ideal_Health_Essentials_Welcome_Packet.pdf",
          content: pdfBase64,
        },
        {
          filename: "Ideal_Health_Essentials_Membership_Agreement.pdf",
          content: agreementPdfBase64,
        },
      ],
      tags: [{ name: "category", value: "essentials-packet" }],
    });
  },
});

export const sendMembershipWelcomeEmail = action({
  args: {
    memberName: v.string(),
    memberEmail: v.string(),
    planName: v.string(),
    effectiveDate: v.string(),
    memberId: v.string(),
    appUrl: v.optional(v.string()),
  },
  handler: async (_ctx: any, args: any) => {
    const { subject, html } = EMAIL_TEMPLATES.welcome.render({
      memberName: args.memberName,
      planName: args.planName,
      effectiveDate: args.effectiveDate,
      memberId: args.memberId,
      portalUrl: args.appUrl ?? getBaseUrl(),
    });

    return await sendViaResendOrThrow({
      to: args.memberEmail,
      subject,
      html,
      tags: [{ name: "category", value: "welcome" }],
    });
  },
});

export const sendMembershipConfirmationEmail = action({
  args: {
    memberName: v.string(),
    memberEmail: v.string(),
    memberId: v.string(),
    planName: v.string(),
    groupCode: v.string(),
    effectiveDate: v.string(),
    processingFee: v.optional(v.string()),
    billingAmount: v.optional(v.string()),
  },
  handler: async (_ctx: any, args: any) => {
    const { subject, html } = EMAIL_TEMPLATES.confirmation.render({
      memberName: args.memberName,
      memberId: args.memberId,
      planName: args.planName,
      groupCode: args.groupCode,
      effectiveDate: args.effectiveDate,
      processingFee: args.processingFee,
      billingAmount: args.billingAmount,
    });

    return await sendViaResendOrThrow({
      to: args.memberEmail,
      subject,
      html,
      tags: [{ name: "category", value: "confirmation" }],
    });
  },
});

export const sendMembershipCancelledEmail = action({
  args: {
    memberName: v.string(),
    memberEmail: v.string(),
    memberId: v.string(),
  },
  handler: async (_ctx: any, args: any) => {
    const { subject, html } = EMAIL_TEMPLATES.cancelled.render({
      memberName: args.memberName,
      memberId: args.memberId,
    });

    return await sendViaResendOrThrow({
      to: args.memberEmail,
      subject,
      html,
      tags: [{ name: "category", value: "cancelled" }],
    });
  },
});

/**
 * Send Eligibility "Set Your Password" Welcome Email
 *
 * Sent to a member who has been provisioned through the eligibility pipeline
 * (employer / sponsor list-bill). Contains the Clerk invitation URL the
 * member must click to choose a password and complete sign-in.
 *
 * This replaces Clerk's default invitation email so we control the
 * branding and Careington/DialCare compliance language.
 *
 * Required env vars: RESEND_API_KEY
 */
export const sendEligibilityWelcomeSetPasswordEmail = action({
  args: {
    memberName: v.string(),
    memberEmail: v.string(),
    invitationUrl: v.string(),
    sponsorName: v.optional(v.string()),
    appUrl: v.optional(v.string()),
  },
  handler: async (_ctx: any, args: any) => {
    const { subject, html } = EMAIL_TEMPLATES["eligibility-set-password"].render({
      memberName: args.memberName,
      invitationUrl: args.invitationUrl,
      sponsorName: args.sponsorName,
      portalUrl: args.appUrl ?? getBaseUrl(),
    });

    return await sendViaResendOrThrow({
      to: args.memberEmail,
      subject,
      html,
      tags: [{ name: "category", value: "eligibility-set-password" }],
    });
  },
});
