/* eslint-disable @typescript-eslint/no-explicit-any */
import { action } from "../_generated/server";
import { v } from "convex/values";
import { getBaseUrl } from "../lib/env";

/**
 * Email Fulfillment Actions
 * Handles sending membership-related emails via Resend
 * Note: Requires RESEND_API_KEY set in environment
 */

/**
 * Send Member Fulfillment Packet Email
 *
 * Generates a 4-page PDF fulfillment packet and sends it to the new member
 * via Resend with the PDF attached.
 *
 * The PDF is generated by the Next.js API route /api/generate-fulfillment-pdf
 * so that @react-pdf/renderer runs in the Node.js environment.
 *
 * Required env vars:
 *   RESEND_API_KEY
 *   NEXT_PUBLIC_APP_URL  (e.g. https://getidealoh.com)
 *   INTERNAL_API_SECRET  (shared secret with Next.js – omit in dev to skip auth)
 */
export const sendFulfillmentPacketEmail = action({
  args: {
    // Member data used to personalise the PDF and email body
    memberName: v.string(),
    memberFirstName: v.string(),
    memberEmail: v.string(),
    memberId: v.string(),
    planName: v.string(),
    groupCode: v.string(),
    effectiveDate: v.string(),
    // Optional fields
    subscriberId: v.optional(v.string()),
    term: v.optional(v.string()),
    memberAddress: v.optional(v.string()),
    periodicCharge: v.optional(v.string()),
    processingFee: v.optional(v.string()),
    memberServicesPhone: v.optional(v.string()),
    memberWebsite: v.optional(v.string()),
    // Allows callers to override the app base URL (useful in tests / staging)
    appUrl: v.optional(v.string()),
  },
  handler: async (_ctx: any, args: any) => {
    const baseUrl = args.appUrl ?? getBaseUrl();

    // ── Step 1: generate the PDF ──────────────────────────────────────────────
    const pdfPayload = {
      memberName: args.memberName,
      memberFirstName: args.memberFirstName,
      memberEmail: args.memberEmail,
      memberId: args.memberId,
      subscriberId: args.subscriberId,
      groupCode: args.groupCode,
      planName: args.planName,
      effectiveDate: args.effectiveDate,
      term: args.term,
      memberAddress: args.memberAddress,
      periodicCharge: args.periodicCharge,
      processingFee: args.processingFee,
      memberServicesPhone: args.memberServicesPhone,
      memberWebsite: args.memberWebsite,
    };

    const pdfHeaders: Record<string, string> = {
      "Content-Type": "application/json",
    };
    const internalSecret = process.env.INTERNAL_API_SECRET;
    if (internalSecret) {
      pdfHeaders["Authorization"] = `Bearer ${internalSecret}`;
    }

    const pdfResponse = await fetch(
      `${baseUrl}/api/generate-fulfillment-pdf`,
      {
        method: "POST",
        headers: pdfHeaders,
        body: JSON.stringify(pdfPayload),
      }
    );

    if (!pdfResponse.ok) {
      const errText = await pdfResponse.text();
      throw new Error(
        `PDF generation failed (${pdfResponse.status}): ${errText}`
      );
    }

    const { pdf: pdfBase64, agreementPdf: agreementPdfBase64 } = await pdfResponse.json();

    // ── Step 2: send via Resend with both PDFs attached ───────────────────────
    const emailResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Ideal Oral Health <noreply@getidealoh.com>",
        to: args.memberEmail,
        replyTo: "support@getidealoh.com",
        subject: "Your Ideal Oral Health Membership Packet & Program Guide",
        html: generateFulfillmentEmailHTML({
          memberFirstName: args.memberFirstName,
          memberId: args.memberId,
          planName: args.planName,
          effectiveDate: args.effectiveDate,
          groupCode: args.groupCode,
          memberServicesPhone: args.memberServicesPhone ?? "801-820-0010",
          portalUrl: baseUrl,
        }),
        attachments: [
          {
            filename: "Ideal_Oral_Health_Membership_Packet.pdf",
            content: pdfBase64,
          },
          {
            filename: "Ideal_Oral_Health_Membership_Agreement.pdf",
            content: agreementPdfBase64,
          },
        ],
      }),
    });

    if (!emailResponse.ok) {
      throw new Error(
        `Resend API error: ${emailResponse.statusText}`
      );
    }

    const emailData = await emailResponse.json();
    return { success: true, emailId: emailData.id };
  },
});

export const sendMembershipWelcomeEmail = action({
  args: {
    memberName: v.string(),
    memberEmail: v.string(),
    planName: v.string(),
    effectiveDate: v.string(),
    memberId: v.string(),
  },
  handler: async (ctx: any, args: any) => {
    try {
      const response = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        },
        body: JSON.stringify({
          from: "Ideal Oral Health <noreply@getidealoh.com>",
          to: args.memberEmail,
          replyTo: "support@getidealoh.com",
          subject: "Welcome to Ideal Oral Health - Your Membership is Active",
          html: generateWelcomeEmailHTML(args),
        }),
      });

      if (!response.ok) {
        throw new Error(`Resend API error: ${response.statusText}`);
      }

      const data = await response.json();
      return { success: true, emailId: data.id };
    } catch (error) {
      console.error("Failed to send welcome email:", error);
      throw error;
    }
  },
});

export const sendMembershipConfirmationEmail = action({
  args: {
    memberName: v.string(),
    memberEmail: v.string(),
    memberId: v.string(),
    planName: v.string(),
    groupCode: v.string(),
    effectiveDate: v.string(),
    processingFee: v.optional(v.string()),
    billingAmount: v.optional(v.string()),
  },
  handler: async (ctx: any, args: any) => {
    try {
      const response = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        },
        body: JSON.stringify({
          from: "Ideal Oral Health <noreply@getidealoh.com>",
          to: args.memberEmail,
          replyTo: "support@getidealoh.com",
          subject: "Ideal Oral Health Membership Confirmation",
          html: generateConfirmationEmailHTML(args),
        }),
      });

      if (!response.ok) {
        throw new Error(`Resend API error: ${response.statusText}`);
      }

      const data = await response.json();
      return { success: true, emailId: data.id };
    } catch (error) {
      console.error("Failed to send confirmation email:", error);
      throw error;
    }
  },
});

export const sendMembershipCancelledEmail = action({
  args: {
    memberName: v.string(),
    memberEmail: v.string(),
    memberId: v.string(),
  },
  handler: async (ctx: any, args: any) => {
    try {
      const response = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        },
        body: JSON.stringify({
          from: "Ideal Oral Health <noreply@getidealoh.com>",
          to: args.memberEmail,
          replyTo: "support@getidealoh.com",
          subject: "Ideal Oral Health Membership Cancelled",
          html: generateCancellationEmailHTML(args),
        }),
      });

      if (!response.ok) {
        throw new Error(`Resend API error: ${response.statusText}`);
      }

      const data = await response.json();
      return { success: true, emailId: data.id };
    } catch (error) {
      console.error("Failed to send cancellation email:", error);
      throw error;
    }
  },
});

export const sendDependentInviteEmail = action({
  args: {
    dependentName: v.string(),
    dependentEmail: v.string(),
    primaryMemberName: v.string(),
    planName: v.string(),
    inviteToken: v.string(),
    appUrl: v.optional(v.string()),
  },
  handler: async (ctx: any, args: any) => {
    const baseUrl = args.appUrl ?? getBaseUrl();
    const claimUrl = `${baseUrl}/health/claim-invite?token=${args.inviteToken}`;
    try {
      const response = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        },
        body: JSON.stringify({
          from: "Ideal Oral Health <noreply@getidealoh.com>",
          to: args.dependentEmail,
          replyTo: "support@getidealoh.com",
          subject: `${args.primaryMemberName} added you to their Ideal Oral Health plan`,
          html: generateDependentInviteEmailHTML({
            dependentName: args.dependentName,
            primaryMemberName: args.primaryMemberName,
            planName: args.planName,
            claimUrl,
          }),
        }),
      });
      if (!response.ok) {
        throw new Error(`Resend API error: ${response.statusText}`);
      }
      const data = await response.json();
      return { success: true, emailId: data.id };
    } catch (error) {
      console.error("Failed to send dependent invite email:", error);
      throw error;
    }
  },
});

// ============================================
// EMAIL TEMPLATE GENERATORS
// ============================================

interface WelcomeEmailData {
  memberName: string;
  memberEmail: string;
  planName: string;
  effectiveDate: string;
  memberId: string;
}

interface ConfirmationEmailData extends WelcomeEmailData {
  groupCode: string;
  processingFee?: string;
  billingAmount?: string;
}

interface CancellationEmailData {
  memberName: string;
  memberEmail: string;
  memberId: string;
}

function generateWelcomeEmailHTML(data: WelcomeEmailData): string {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0;">Welcome to Ideal Oral Health</h1>
        <p style="margin: 10px 0 0 0; font-size: 14px;">Your membership is now active</p>
      </div>

      <div style="padding: 30px; background: #f9f9f9; border-radius: 0 0 8px 8px;">
        <p>Hi ${data.memberName},</p>

        <p>Thank you for enrolling in <strong>${data.planName}</strong>! We're excited to have you as a member of the Ideal Oral Health family.</p>

        <div style="background: white; padding: 15px; border-left: 4px solid #667eea; margin: 20px 0;">
          <h3 style="margin-top: 0; color: #667eea;">Your Membership Details</h3>
          <p style="margin: 5px 0;"><strong>Member ID:</strong> ${data.memberId}</p>
          <p style="margin: 5px 0;"><strong>Plan:</strong> ${data.planName}</p>
          <p style="margin: 5px 0;"><strong>Effective Date:</strong> ${data.effectiveDate}</p>
        </div>

        <h3 style="color: #667eea;">What You Get:</h3>
        <ul style="line-height: 1.8;">
          <li><strong>AI Oral Scan:</strong> Monitor your dental health from home</li>
          <li><strong>DialCare Teledentistry:</strong> 24/7/365 virtual consultations</li>
          <li><strong>Dental Discount Network:</strong> Save 20-50% on dental procedures</li>
          <li><strong>No Insurance Hassles:</strong> Simple discount pricing</li>
        </ul>

        <h3 style="color: #667eea;">Getting Started:</h3>
        <ol style="line-height: 1.8;">
          <li>Log in to your <a href="https://www.getidealoh.com/health/dashboard" style="color: #667eea; text-decoration: none;">Member Portal</a> for your AI Oral Scan and digital ID card</li>
          <li>Visit <a href="https://www.getidealoh.com" style="color: #667eea; text-decoration: none;">getidealoh.com</a> or call (800) 290-0523 to find a dentist near you</li>
          <li>Present your ID card to receive discounts</li>
        </ol>

        <div style="background: #e3f2fd; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <p style="margin: 0;"><strong>Need Help?</strong></p>
          <p style="margin: 5px 0;">
            Phone: <a href="tel:801-820-0010" style="color: #667eea; text-decoration: none;">801-820-0010</a> | 
            Email: <a href="mailto:info@getidealoh.com" style="color: #667eea; text-decoration: none;">info@getidealoh.com</a>
          </p>
        </div>

        <p>Best regards,<br><strong>The Ideal Oral Health Team</strong></p>
      </div>
    </div>
  `;
}

function generateConfirmationEmailHTML(data: ConfirmationEmailData): string {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <div style="background: #2c3e50; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0;">Membership Confirmation</h1>
      </div>

      <div style="padding: 30px; background: #f9f9f9; border-radius: 0 0 8px 8px;">
        <p>Thank you for your enrollment, ${data.memberName}!</p>

        <div style="background: white; padding: 20px; border-radius: 5px; margin: 20px 0; border: 2px solid #2c3e50;">
          <h3 style="margin-top: 0; color: #2c3e50;">Enrollment Summary</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #eee;">
              <td style="padding: 10px 0; font-weight: bold;">Member ID:</td>
              <td style="padding: 10px 0; text-align: right;">${data.memberId}</td>
            </tr>
            <tr style="border-bottom: 1px solid #eee;">
              <td style="padding: 10px 0; font-weight: bold;">Plan:</td>
              <td style="padding: 10px 0; text-align: right;">${data.planName}</td>
            </tr>
            <tr style="border-bottom: 1px solid #eee;">
              <td style="padding: 10px 0; font-weight: bold;">Plan Code:</td>
              <td style="padding: 10px 0; text-align: right;">${data.groupCode}</td>
            </tr>
            <tr style="border-bottom: 1px solid #eee;">
              <td style="padding: 10px 0; font-weight: bold;">Effective Date:</td>
              <td style="padding: 10px 0; text-align: right;">${data.effectiveDate}</td>
            </tr>
            ${data.billingAmount ? `
            <tr style="border-bottom: 1px solid #eee;">
              <td style="padding: 10px 0; font-weight: bold;">Billing Amount:</td>
              <td style="padding: 10px 0; text-align: right;">${data.billingAmount}</td>
            </tr>
            ` : ""}
            ${data.processingFee ? `
            <tr>
              <td style="padding: 10px 0; font-weight: bold;">Processing Fee:</td>
              <td style="padding: 10px 0; text-align: right;">${data.processingFee}</td>
            </tr>
            ` : ""}
          </table>
        </div>

        <p>Your membership is effective immediately and you can start using your benefits right away!</p>

        <div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ffc107;">
          <p style="margin: 0;"><strong>Cancellation Policy:</strong></p>
          <p style="margin: 10px 0 0 0; font-size: 13px;">
            30-day cancellation window available. Contact: <a href="tel:801-820-0010" style="color: #ffc107; text-decoration: none;">801-820-0010</a>
          </p>
        </div>

        <p>Questions? We're here to help!</p>
      </div>
    </div>
  `;
}

function generateCancellationEmailHTML(data: CancellationEmailData): string {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <div style="background: #c0392b; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0;">Membership Cancelled</h1>
      </div>

      <div style="padding: 30px; background: #f9f9f9; border-radius: 0 0 8px 8px;">
        <p>Hi ${data.memberName},</p>

        <p>Your Ideal Oral Health membership has been cancelled as requested.</p>

        <div style="background: white; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #c0392b;">
          <h3 style="margin-top: 0; color: #c0392b;">Cancellation Details</h3>
          <p style="margin: 5px 0;"><strong>Member ID:</strong> ${data.memberId}</p>
          <p style="margin: 5px 0;"><strong>Cancellation Date:</strong> ${new Date().toLocaleDateString()}</p>
        </div>

        <p>You will continue to have access to your benefits for the remainder of the period for which you've already paid.</p>

        <p style="font-size: 12px; color: #666;">
          Thank you for being part of our community. We hope to welcome you back in the future!
        </p>
      </div>
    </div>
  `;
}

function generateDependentInviteEmailHTML(data: {
  dependentName: string;
  primaryMemberName: string;
  planName: string;
  claimUrl: string;
}): string {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <div style="background: linear-gradient(135deg, #0066CC 0%, #14b8a6 100%); color: white; padding: 24px 20px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0; font-size: 24px;">You're Invited!</h1>
        <p style="margin: 10px 0 0 0; font-size: 15px; opacity: 0.9;">Family plan access from Ideal Oral Health</p>
      </div>

      <div style="padding: 32px; background: #f9fafb; border-radius: 0 0 8px 8px;">
        <p style="font-size: 16px;">Hi ${data.dependentName},</p>

        <p style="font-size: 15px; line-height: 1.6;">
          <strong>${data.primaryMemberName}</strong> has added you to their
          <strong>${data.planName}</strong> plan. As a family member, you'll get
          full access to all plan benefits — with no separate billing.
        </p>

        <div style="background: white; border: 1px solid #e5e7eb; border-radius: 10px; padding: 20px; margin: 24px 0; text-align: center;">
          <p style="font-size: 15px; color: #374151; margin: 0 0 16px 0;">
            Click the button below to create your account and activate your access.
          </p>
          <a href="${data.claimUrl}"
            style="display: inline-block; padding: 14px 32px; background: #0066CC; color: white; font-weight: 700; font-size: 16px; text-decoration: none; border-radius: 8px;">
            Accept &amp; Get Access
          </a>
          <p style="font-size: 12px; color: #9ca3af; margin: 16px 0 0 0;">
            This link expires in 30 days.
          </p>
        </div>

        <h3 style="color: #0066CC; font-size: 15px;">What You Get:</h3>
        <ul style="line-height: 1.8; font-size: 14px; color: #4b5563;">
          <li><strong>AI Oral Scan:</strong> Monitor dental health from home</li>
          <li><strong>DialCare Teledentistry:</strong> 24/7 virtual consultations with licensed dentists</li>
          <li><strong>Dental Discount Network:</strong> Save 20–50% on dental procedures at thousands of providers nationwide</li>
          <li><strong>No separate charge:</strong> Your access is included under ${data.primaryMemberName}'s plan</li>
        </ul>

        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />

        <p style="font-size: 13px; color: #6b7280; line-height: 1.5;">
          If you don't want to be added to this plan, you can simply ignore this email.
          Questions? Contact us at <a href="mailto:info@getidealoh.com" style="color: #0066CC; text-decoration: none;">info@getidealoh.com</a>
          or <a href="tel:801-820-0010" style="color: #0066CC; text-decoration: none;">801-820-0010</a>.
        </p>

        <p style="font-size: 11px; color: #9ca3af; margin-top: 16px;">
          This plan is not insurance. Access link: <a href="${data.claimUrl}" style="color: #9ca3af;">${data.claimUrl}</a>
        </p>
      </div>
    </div>
  `;
}

interface FulfillmentEmailData {
  memberFirstName: string;
  memberId: string;
  planName: string;
  effectiveDate: string;
  groupCode: string;
  memberServicesPhone: string;
  portalUrl: string;
}

function generateFulfillmentEmailHTML(data: FulfillmentEmailData): string {
  const BLUE = "#0066CC";
  const TEAL = "#14b8a6";
  const CYAN = "#0d9de0";
  return `
    <div style="font-family: Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #333; background: #f9fafb;">
      <!-- Header -->
      <div style="background: linear-gradient(135deg, #1E88E5 0%, #35C48A 100%); color: white; padding: 28px 24px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0; font-size: 22px;">Your Membership Packet &amp; Program Guide</h1>
        <p style="margin: 8px 0 0; font-size: 14px; opacity: 0.9;">Ideal Oral Health — AI Dental Scan &middot; Teledentistry &middot; Dental Savings</p>
      </div>

      <div style="padding: 28px 24px;">
        <p style="font-size: 16px; margin-bottom: 8px;">Hi ${data.memberFirstName},</p>

        <p style="font-size: 14px; line-height: 1.7;">
          Your enrollment is confirmed and your membership is <strong>active as of ${data.effectiveDate}</strong>.
          Your complete member fulfillment packet and your membership agreement are both attached to this email as PDFs.
        </p>

        <!-- Membership Snapshot -->
        <div style="background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 18px; margin: 20px 0;">
          <h3 style="margin-top: 0; color: #1E88E5; font-size: 14px;">Your Membership Snapshot</h3>
          <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 8px 0; color: #666;">Member ID</td>
              <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.memberId}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 8px 0; color: #666;">Plan</td>
              <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.planName}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f0f0f0;">
              <td style="padding: 8px 0; color: #666;">Group Code</td>
              <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.groupCode}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #666;">Effective Date</td>
              <td style="padding: 8px 0; font-weight: bold; text-align: right;">${data.effectiveDate}</td>
            </tr>
          </table>
        </div>

        <h3 style="color: #1E88E5; font-size: 14px;">What's in your packet:</h3>
        <ul style="font-size: 13px; line-height: 2.0; color: #374151; padding-left: 20px;">
          <li>Welcome letter &amp; member summary card</li>
          <li>AI Oral Scan &mdash; how to access and use</li>
          <li>DialCare Teledentistry program details &amp; how to access</li>
          <li>Dental Discount Network program details &amp; how to access savings</li>
          <li>Sample schedule of dental services and member-pay amounts</li>
          <li>Member ID card (front &amp; back)</li>
        </ul>
        <p style="font-size: 13px; color: #374151; line-height: 1.7;">
          <strong>Your Membership Agreement</strong> is attached as a separate PDF for your records.
        </p>

        <!-- ─── How to Use Your Program ───────────────────────────────── -->
        <div style="border-top: 2px solid #e2e8f0; margin: 28px 0 20px; padding-top: 24px;">
          <h2 style="margin: 0 0 6px; font-size: 18px; color: #0f172a;">How to Use Your Program</h2>
          <p style="margin: 0 0 16px; font-size: 13px; color: #6b7280;">Your membership includes 3 core benefits — here's how to get started.</p>
        </div>

        <!-- Benefit 1: AI Dental Scan -->
        <div style="background: white; border: 1px solid #e5e7eb; border-radius: 10px; padding: 20px; margin-bottom: 16px;">
          <h3 style="margin: 0 0 10px; font-size: 15px; color: ${BLUE};">1. AI Dental Scan</h3>
          <ol style="margin: 0; padding: 0 0 0 20px; font-size: 13px; line-height: 2.0; color: #374151;">
            <li>Log in to your <a href="${data.portalUrl}/health/dashboard" style="color: ${BLUE}; text-decoration: none;">Member Portal</a> and open the <strong>Oral Scan</strong> tab.</li>
            <li>Upload or take a clear photo of your teeth.</li>
            <li>Review your results and any recommended next steps.</li>
          </ol>
          <p style="font-size: 12px; color: #6b7280; margin: 10px 0 0; line-height: 1.5;">
            <strong>Best for:</strong> Spotting possible problem areas, monitoring visible changes, and knowing when to seek follow-up care.
          </p>
          <p style="font-size: 11px; color: #9ca3af; margin: 6px 0 0;">Note: The AI scan is a screening tool — not a clinical diagnosis. Always consult a licensed dentist.</p>
        </div>

        <!-- Benefit 2: Teledentistry -->
        <div style="background: white; border: 1px solid #e5e7eb; border-radius: 10px; padding: 20px; margin-bottom: 16px;">
          <h3 style="margin: 0 0 10px; font-size: 15px; color: ${CYAN};">2. Teledentistry (DialCare)</h3>
          <ol style="margin: 0; padding: 0 0 0 20px; font-size: 13px; line-height: 2.0; color: #374151;">
            <li>Open the <strong>Teledentistry</strong> tab in your portal, or visit <a href="https://www.dialcare.com" style="color: ${CYAN}; text-decoration: none;">dialcare.com</a>.</li>
            <li>Request or schedule a virtual consultation (available 24/7).</li>
            <li>Share your concern, scan results, or symptoms with the dentist.</li>
            <li>Receive professional guidance on what to do next.</li>
          </ol>
          <p style="font-size: 12px; color: #6b7280; margin: 10px 0 0; line-height: 1.5;">
            <strong>Best for:</strong> Questions about dental concerns, guidance after an AI scan, and deciding if in-person care is needed.
          </p>
          <div style="background: #FFF8E1; border-left: 3px solid #F9A825; padding: 10px 12px; margin-top: 10px; border-radius: 4px;">
            <p style="font-size: 12px; color: #374151; margin: 0; line-height: 1.5;">
              <strong style="color: #F9A825;">Look for your DialCare email:</strong>
              Shortly after enrollment, you will receive a separate &ldquo;Register Your Account&rdquo; email directly from DialCare. Use it to set up your teledentistry account. If you don&rsquo;t see it, check your spam/junk folder or call DialCare at (855) 335-2255.
            </p>
          </div>
        </div>

        <!-- Benefit 3: Dental Discount Network -->
        <div style="background: white; border: 1px solid #e5e7eb; border-radius: 10px; padding: 20px; margin-bottom: 16px;">
          <h3 style="margin: 0 0 10px; font-size: 15px; color: ${TEAL};">3. Dental Discount Network</h3>
          <ol style="margin: 0; padding: 0 0 0 20px; font-size: 13px; line-height: 2.0; color: #374151;">
            <li>Search for a participating provider at <a href="https://www.getidealoh.com" style="color: ${TEAL}; text-decoration: none;">getidealoh.com</a> or call (800) 290-0523.</li>
            <li>Confirm the provider accepts the discount program <strong>before</strong> your visit.</li>
            <li>Present your Member ID card at your appointment.</li>
            <li>Pay the discounted member amount directly at time of service.</li>
          </ol>
          <p style="font-size: 12px; color: #6b7280; margin: 10px 0 0; line-height: 1.5;">
            <strong>Best for:</strong> Routine dental care, savings on eligible services, and finding participating providers.
          </p>
        </div>

        <!-- Recommended order -->
        <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 10px; padding: 20px; margin-bottom: 16px;">
          <h3 style="margin: 0 0 10px; font-size: 14px; color: ${BLUE};">Recommended Order</h3>
          <p style="font-size: 13px; line-height: 1.7; color: #374151; margin: 0;">
            For the best results: <strong>Start with an AI Scan</strong> to understand any visible areas of concern,
            then <strong>use Teledentistry</strong> if you have questions, and
            <strong>use the Discount Network</strong> when you're ready for in-person care.
          </p>
        </div>

        <!-- FAQ -->
        <div style="background: white; border: 1px solid #e5e7eb; border-radius: 10px; padding: 20px; margin-bottom: 16px;">
          <h3 style="margin: 0 0 14px; font-size: 14px; color: #0f172a;">Frequently Asked Questions</h3>

          <p style="font-size: 13px; font-weight: 700; color: #374151; margin: 0 0 4px;">Do I need my member ID at my appointment?</p>
          <p style="font-size: 13px; color: #6b7280; margin: 0 0 14px; line-height: 1.5;">Yes. Present your member ID card (or the digital card from your dashboard) so the provider can apply your discounts.</p>

          <p style="font-size: 13px; font-weight: 700; color: #374151; margin: 0 0 4px;">When do my benefits begin?</p>
          <p style="font-size: 13px; color: #6b7280; margin: 0 0 14px; line-height: 1.5;">Benefits are activated within 24 hours of enrollment.</p>

          <p style="font-size: 13px; font-weight: 700; color: #374151; margin: 0 0 4px;">Is the AI scan a diagnosis?</p>
          <p style="font-size: 13px; color: #6b7280; margin: 0 0 14px; line-height: 1.5;">No. It is a screening tool. Always consult a licensed dentist for professional evaluation.</p>

          <p style="font-size: 13px; font-weight: 700; color: #374151; margin: 0 0 4px;">How do I know what services are eligible for savings?</p>
          <p style="font-size: 13px; color: #6b7280; margin: 0 0 0; line-height: 1.5;">Your attached packet includes a sample schedule. You can also ask any participating provider for a discounted treatment plan.</p>
        </div>

        <!-- CTA + QR Code -->
        <div style="text-align: center; margin: 24px 0 16px;">
          <a href="${data.portalUrl}/health/dashboard" style="display: inline-block; padding: 14px 36px; background: ${BLUE}; color: white; font-weight: 700; font-size: 15px; text-decoration: none; border-radius: 8px;">
            Go to Your Member Portal
          </a>
          <div style="margin-top: 16px;">
            <p style="font-size: 12px; color: #6b7280; margin: 0 0 8px;">Or scan this QR code to open your dashboard:</p>
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent("https://www.getidealoh.com/health/dashboard")}" alt="QR Code to Member Dashboard" width="150" height="150" style="border: 1px solid #e5e7eb; border-radius: 8px;" />
          </div>
        </div>

        <!-- Support -->
        <div style="background: #EAF4FD; border-radius: 6px; padding: 14px; margin-bottom: 12px; font-size: 13px;">
          <strong>Need help?</strong> Call Member Services at
          <a href="tel:${data.memberServicesPhone}" style="color: #1E88E5; text-decoration: none;">${data.memberServicesPhone}</a>
          or email <a href="mailto:support@getidealoh.com" style="color: #1E88E5; text-decoration: none;">support@getidealoh.com</a>.
          Mon–Fri, 8am–6pm CT.
        </div>

        <!-- Disclaimer -->
        <p style="font-size: 11px; color: #9ca3af; line-height: 1.5; margin: 0;">
          This plan is not insurance. Members are responsible for payment at the time of service
          and receive access to negotiated discounts through participating providers.
          The range of discounts varies by provider and service.
        </p>
      </div>
    </div>
  `;
}
